/**
 * TechLeadAnalyst Schemas & Validation Contracts
 * Generated by COREPACK Compiler Engine (v2.0)
 * Enforces deterministic parsing, explicit calibration boundaries, and strict non-negative integer limits.
 */

import { z } from 'zod';

/**
 * Standard Multi-Agent Handoff Envelope Schema
 */
export const AgentHandoffEnvelopeSchema = z.object({
  sender_agent: z.string().min(1).describe('The originating agent identifier'),
  target_agent: z.string().min(1).describe('Target receiver or router node'),
  is_provisional: z.boolean().default(false).describe('Flag indicating inferred or estimated parameters'),
  confidence_calibration: z.enum(['fact', 'inference', 'guess']).describe('Highest risk uncertainty classification'),
  payload: z.record(z.string(), z.any()).describe('The core domain execution output'),
  timestamp: z.string().datetime().describe('ISO 8601 UTC timestamp of emission'),
});

export type AgentHandoffEnvelope = z.infer<typeof AgentHandoffEnvelopeSchema>;

/**
 * Ingress Gateway Payload Schema for TechLead-Analyst
 */
export const TechLeadAnalystIngressPayloadSchema = z.object({
  request_id: z.string().uuid().describe('Unique transaction or audit ID'),
  session_id: z.string().min(1).describe('Target orchestration session'),
  inputs: z.record(z.string(), z.any()).describe('Domain input variables'),
  is_provisional: z.boolean().default(false).describe('Provisional state marker'),
  created_at: z.string().datetime().describe('Timestamp of ingress'),
});

export type TechLeadAnalystIngressPayload = z.infer<typeof TechLeadAnalystIngressPayloadSchema>;

/**
 * Tool Parameter Schema: auditArchitectureComplexity
 */
export const auditArchitectureComplexityParamsSchema = z.object({
  topologyJson: z.string().describe('Serialized JSON graph of microservice nodes and data connections'),
  maxServiceDepth: z.number().int().nonnegative().optional().describe('Maximum allowable call chain depth before flagging latency risks'),
});

export type auditArchitectureComplexityParams = z.infer<typeof auditArchitectureComplexityParamsSchema>;

/**
 * Tool Parameter Schema: verifyIdempotencyGuarantees
 */
export const verifyIdempotencyGuaranteesParamsSchema = z.object({
  endpointCode: z.string().describe('TypeScript / Node.js route handler snippet'),
  enforceAtomicLock: z.boolean().optional().describe('Whether atomic distributed lock acquisition is mandated'),
  lockTtlSeconds: z.number().int().positive().optional().describe('TTL in seconds for distributed redis lock'),
});

export type verifyIdempotencyGuaranteesParams = z.infer<typeof verifyIdempotencyGuaranteesParamsSchema>;

/**
 * Tool Parameter Schema: runDiagnosticDryRun
 */
export const runDiagnosticDryRunParamsSchema = z.object({
  commandScript: z.string().describe('The bash or deployment script proposed for dry run execution'),
  requireFailFast: z.boolean().default(true).describe('Verifies set -euo pipefail is active'),
});

export type runDiagnosticDryRunParams = z.infer<typeof runDiagnosticDryRunParamsSchema>;

/**
 * Financial & Quantitative Double-Entry Ledger Schema
 * Guarantees zero floating-point arithmetic drift by enforcing all quantities in integer cents.
 */
export const LedgerEntrySchema = z.object({
  entry_id: z.string().uuid(),
  account_id: z.string().min(1),
  direction: z.enum(['DEBIT', 'CREDIT']),
  amount_cents: z.number().int().nonnegative().describe('Integer cents balance (no floating-point values)'),
  currency: z.string().length(3).default('USD'),
  memo: z.string().min(1),
});

export type LedgerEntry = z.infer<typeof LedgerEntrySchema>;

export const LedgerBatchAuditSchema = z.object({
  batch_id: z.string().uuid(),
  entries: z.array(LedgerEntrySchema).min(2),
  balanced: z.boolean().describe('Must equal sum(DEBITS) === sum(CREDITS)'),
  total_debit_cents: z.number().int().nonnegative(),
  total_credit_cents: z.number().int().nonnegative(),
});

export type LedgerBatchAudit = z.infer<typeof LedgerBatchAuditSchema>;

/**
 * Deterministic Egress Verification Gate
 */
export function verifyEgressIntegrity(payload: unknown): boolean {
  try {
    const parsed = AgentHandoffEnvelopeSchema.parse(payload);
    return parsed.is_provisional !== undefined && parsed.confidence_calibration !== undefined;
  } catch {
    return false;
  }
}
