import React, { useState } from 'react';
import {
  Layers,
  Copy,
  Check,
  Download,
  CheckCircle2,
  AlertOctagon,
  AlertTriangle,
  FileCode,
  FileText,
  ShieldCheck,
  Sparkles,
} from 'lucide-react';
import { CorepackConfig, CompiledArtifacts } from '../types';
import { compileAllArtifacts } from '../utils/compiler';

interface CompiledArtifactsTabProps {
  config: CorepackConfig;
}

export const CompiledArtifactsTab: React.FC<CompiledArtifactsTabProps> = ({ config }) => {
  const [activeFile, setActiveFile] = useState<'prompt' | 'manifest' | 'schemas' | 'tests'>('prompt');
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  const artifacts = compileAllArtifacts(config);
  const { defectValidationResult } = artifacts;

  const handleCopy = (content: string, key: string) => {
    navigator.clipboard.writeText(content);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleDownload = (filename: string, content: string) => {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="flex items-center justify-between bg-slate-900/90 p-4 rounded-xl border border-slate-800">
        <div>
          <h2 className="text-base font-semibold text-slate-100 flex items-center gap-2">
            <Layers className="w-5 h-5 text-indigo-400" />
            Compiled Corepack Artifacts & Defect Validation Gate
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Production-ready compiled code artifacts generated by the COREPACK Builder Engine (v2.0).
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => handleDownload(`${config.metadata.id}-bundle.json`, JSON.stringify(config, null, 2))}
            className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold rounded-lg shadow-sm flex items-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            Download Complete Bundle
          </button>
        </div>
      </div>

      {/* Pre-Flight Defect Validation Gate Checklist */}
      <div className="bg-slate-900/80 p-5 rounded-xl border border-slate-800 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <h3 className="text-sm font-bold text-slate-200">
              Pre-Flight Defect Validation Gate (Automated Compiler Audit)
            </h3>
          </div>
          <span
            className={`px-2.5 py-0.5 text-xs font-bold rounded-full border ${
              defectValidationResult.passed
                ? 'bg-emerald-950 text-emerald-300 border-emerald-800'
                : 'bg-rose-950 text-rose-300 border-rose-800'
            }`}
          >
            {defectValidationResult.passed ? 'ALL CHECKS PASSED (DEPLOY READY)' : 'DEFECTS DETECTED'}
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.hasSubstrateBinding ? 'text-emerald-400' : 'text-rose-500'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">Substrate Binding Contract</span>
              <span className="text-[11px] text-slate-400">
                Bound strictly to <code>system-prompt-v3.md</code>
              </span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.hasRevenueGradeSections ? 'text-emerald-400' : 'text-rose-500'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">Revenue-Grade Output Protocol</span>
              <span className="text-[11px] text-slate-400">
                Hardcoded Section I, II, and III markdown schemas
              </span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.bannedPolitenessBoilerplate ? 'text-emerald-400' : 'text-amber-400'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">Zero Politeness Boilerplate</span>
              <span className="text-[11px] text-slate-400">
                Stripped conversational greetings and polite noise
              </span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.hasThreeTierConfidenceMatrix ? 'text-emerald-400' : 'text-rose-500'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">3-Tier Confidence Audit</span>
              <span className="text-[11px] text-slate-400">
                Verified Facts, Recollections, and Guesses isolated
              </span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.hasIdempotentFailFastDirectives ? 'text-emerald-400' : 'text-amber-400'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">Fail-Fast Directives</span>
              <span className="text-[11px] text-slate-400">
                Idempotency and <code>set -euo pipefail</code> safety
              </span>
            </div>
          </div>

          <div className="p-3 rounded-lg bg-slate-950 border border-slate-800/80 flex items-start gap-2.5">
            <CheckCircle2
              className={`w-4 h-4 mt-0.5 ${
                defectValidationResult.checklist.hasExplicitVerificationStep ? 'text-emerald-400' : 'text-amber-400'
              }`}
            />
            <div>
              <span className="text-xs font-bold text-slate-200 block">Actionable Verification Step</span>
              <span className="text-[11px] text-slate-400">
                Audit includes dry-run validation steps
              </span>
            </div>
          </div>
        </div>

        {defectValidationResult.errors.length > 0 && (
          <div className="p-3 bg-rose-950/60 border border-rose-800 rounded-lg text-xs text-rose-300 space-y-1">
            <div className="font-bold flex items-center gap-1.5">
              <AlertOctagon className="w-4 h-4 text-rose-400" />
              Critical Validation Errors:
            </div>
            <ul className="list-disc list-inside space-y-0.5">
              {defectValidationResult.errors.map((err, i) => (
                <li key={i}>{err}</li>
              ))}
            </ul>
          </div>
        )}
      </div>

      {/* Artifact Viewer with Sub-Tabs */}
      <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden shadow-lg">
        <div className="flex items-center justify-between px-4 py-2 bg-slate-950 border-b border-slate-800">
          <div className="flex space-x-1">
            {[
              { id: 'prompt', label: 'SYSTEM_PROMPT.md', ext: 'markdown' },
              { id: 'manifest', label: 'SKILL_MANIFEST.yml', ext: 'yaml' },
              { id: 'schemas', label: 'schemas.ts (Zod)', ext: 'typescript' },
              { id: 'tests', label: 'TEST_PROMPTS.md', ext: 'markdown' },
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveFile(tab.id as any)}
                className={`px-3 py-1.5 text-xs font-mono font-medium rounded-lg transition-colors ${
                  activeFile === tab.id
                    ? 'bg-indigo-600 text-white shadow-sm'
                    : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                let content = artifacts.systemPromptMd;
                let fname = 'SYSTEM_PROMPT.md';
                if (activeFile === 'manifest') {
                  content = artifacts.skillManifestYml;
                  fname = 'SKILL_MANIFEST.yml';
                }
                if (activeFile === 'schemas') {
                  content = artifacts.schemasTs;
                  fname = 'schemas.ts';
                }
                if (activeFile === 'tests') {
                  content = artifacts.testPromptsMd;
                  fname = 'TEST_PROMPTS.md';
                }
                handleCopy(content, activeFile);
              }}
              className="inline-flex items-center gap-1.5 px-3 py-1 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-md transition-colors"
            >
              {copiedKey === activeFile ? (
                <>
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-3.5 h-3.5" />
                  Copy File
                </>
              )}
            </button>

            <button
              onClick={() => {
                let content = artifacts.systemPromptMd;
                let fname = `${config.metadata.id}-SYSTEM_PROMPT.md`;
                if (activeFile === 'manifest') {
                  content = artifacts.skillManifestYml;
                  fname = `${config.metadata.id}-SKILL_MANIFEST.yml`;
                }
                if (activeFile === 'schemas') {
                  content = artifacts.schemasTs;
                  fname = `${config.metadata.id}-schemas.ts`;
                }
                if (activeFile === 'tests') {
                  content = artifacts.testPromptsMd;
                  fname = `${config.metadata.id}-TEST_PROMPTS.md`;
                }
                handleDownload(fname, content);
              }}
              className="inline-flex items-center gap-1.5 px-3 py-1 text-xs font-medium text-slate-200 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-md transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              Download
            </button>
          </div>
        </div>

        {/* Code Content View */}
        <pre className="p-6 text-xs font-mono text-slate-300 bg-slate-950 overflow-x-auto whitespace-pre-wrap leading-relaxed max-h-[650px] scrollbar-thin">
          {activeFile === 'prompt' && artifacts.systemPromptMd}
          {activeFile === 'manifest' && artifacts.skillManifestYml}
          {activeFile === 'schemas' && artifacts.schemasTs}
          {activeFile === 'tests' && artifacts.testPromptsMd}
        </pre>
      </div>
    </div>
  );
};
